@hostname=http://localhost:5000

get {{hostname}}


###
post {{hostname}}/api/auth/register
Content-Type: application/json

{
    "username":"1comce",
    "email":"mainvox9421@gmail.com",
    "password":"123"
}

###

post {{hostname}}/api/auth/login
Content-Type: application/json

{
    "username":"1comce",
    "password":"123"
}